# Generated by Django 5.2.5 on 2025-09-09 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('external_id', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('info', 'info'), ('warn', 'warn'), ('crit', 'crit')], default='warn', max_length=16)),
                ('message', models.TextField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vitals.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('heart_rate_bpm', models.FloatField(blank=True, null=True)),
                ('spo2_percent', models.FloatField(blank=True, null=True)),
                ('signal_quality', models.IntegerField(default=0)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='vitals.athlete')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['athlete', 'timestamp'], name='vitals_read_athlete_93d2bc_idx')],
            },
        ),
    ]
